import 'dotenv/config';
import assert from 'node:assert/strict';
import { test } from 'node:test';
import * as XLSX from 'xlsx';
import { pool } from '../src/config/database.js';
import { app } from '../src/app.js';
import { testCatalog } from './support/fixtures.js';

test('substituição explícita não duplica, pode ser desfeita e é reconhecida na reimportação', async () => {
  const c = await testCatalog(); const old = await pool.query<{ id: string }>(`INSERT INTO abastecimentos (origem_sistema,identificador_externo,data_hora,produto_id,obra_id,tipo_destinatario,frota_id,identificacao_original,placa_original,frota_original,litros,valor_total,bico_codigo_original,arquivo_nome_original,payload_original) VALUES ('POLIFROTA','990000','2026-09-04 06:05',$1,$2,'FROTA',$3,$4,$5,$4,190,1160.9000,'21','replacement-fixture.xlsx','{}') RETURNING id`, [c.product.id, c.nextObra.id, c.fleet.id, c.fleet.codigo, c.fleet.placa]);
  const sheet = XLSX.utils.aoa_to_sheet([['Nro. Abast.','Data','Placa','Frota','Abastecida','Valor Total($)','Km/Hr.','Bico','Frentista'],['990001','04/09/2026 06:05',c.fleet.placa,c.fleet.codigo,'190','1160.90','112898','21','Teste']]); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, 'Relatorio'); const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
  const before = Number((await pool.query('SELECT COUNT(*)::int count FROM abastecimentos')).rows[0].count); const server = app.listen(0); const address = server.address(); assert.ok(address && typeof address === 'object'); const base = `http://127.0.0.1:${address.port}`; let importId = ''; let nextImportId = ''; let oldId = old.rows[0]!.id;
  try {
    const form = new FormData(); form.append('arquivo', new Blob([buffer]), `replacement-${Date.now()}.xlsx`); const analyzed = await fetch(`${base}/abastecimento/importacoes/polifrota/analisar`, { method: 'POST', body: form }); const preview = await analyzed.json() as { id: string; items: Array<{ id: string; status_preview: string }> }; assert.equal(analyzed.status, 201); importId = preview.id; const item = preview.items[0]!;
    const linked = await fetch(`${base}/abastecimento/importacoes/${importId}/itens/${item.id}/substituicao`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ abastecimento_id: oldId }) }); const linkedBody = await linked.json() as { status_preview: string; substituicao_identificador_principal: string }; assert.equal(linked.status, 200); assert.equal(linkedBody.status_preview, 'SUBSTITUICAO'); assert.equal(linkedBody.substituicao_identificador_principal, '990000');
    const undone = await fetch(`${base}/abastecimento/importacoes/${importId}/itens/${item.id}/substituicao`, { method: 'DELETE' }); const undoneBody = await undone.json() as { status_preview: string; substituicao_abastecimento_id: string | null }; assert.equal(undone.status, 200); assert.equal(undoneBody.status_preview, 'PENDENTE_OBRA'); assert.equal(undoneBody.substituicao_abastecimento_id, null);
    const relinked = await fetch(`${base}/abastecimento/importacoes/${importId}/itens/${item.id}/substituicao`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ abastecimento_id: oldId }) }); assert.equal(relinked.status, 200);
    const confirmed = await fetch(`${base}/abastecimento/importacoes/${importId}/confirmar`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); const confirmation = await confirmed.json() as { importadas: number; substituicoes: number; status: string }; assert.equal(confirmed.status, 200); assert.deepEqual({ importadas: confirmation.importadas, substituicoes: confirmation.substituicoes, status: confirmation.status }, { importadas: 0, substituicoes: 1, status: 'CONCLUIDA' }); assert.equal(Number((await pool.query('SELECT COUNT(*)::int count FROM abastecimentos')).rows[0].count), before);
    const alias = await pool.query<{ abastecimento_id: string }>("SELECT abastecimento_id FROM abastecimento_substituicoes WHERE origem_sistema='POLIFROTA' AND identificador_externo='990001'"); assert.equal(alias.rows[0]?.abastecimento_id, oldId);
    const preserved = (await pool.query<{ obra_id: string; bico_codigo_original: string; valor_total: string }>('SELECT obra_id,bico_codigo_original,valor_total FROM abastecimentos WHERE id=$1', [oldId])).rows[0]!; assert.equal(preserved.obra_id, c.nextObra.id); assert.equal(preserved.bico_codigo_original, '21'); assert.equal(Number(preserved.valor_total), 1160.9);
    const nextForm = new FormData(); nextForm.append('arquivo', new Blob([buffer]), `replacement-next-${Date.now()}.xlsx`); const next = await fetch(`${base}/abastecimento/importacoes/polifrota/analisar`, { method: 'POST', body: nextForm }); const nextBody = await next.json() as { id: string; items: Array<{ status_preview: string; substituicao_identificador_principal: string }> }; assert.equal(next.status, 201); nextImportId = nextBody.id; assert.equal(nextBody.items[0]?.status_preview, 'SUBSTITUICAO_JA_REGISTRADA'); assert.equal(nextBody.items[0]?.substituicao_identificador_principal, '990000');
    const duplicateLink = await fetch(`${base}/abastecimento/importacoes/${nextBody.id}/itens/${nextBody.items[0]!.id}/substituicao`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ abastecimento_id: oldId }) }); assert.equal(duplicateLink.status, 409); const undoImport = await fetch(`${base}/abastecimento/importacoes/${nextBody.id}/itens/${nextBody.items[0]!.id}/substituicao`, { method: 'DELETE' }); assert.equal(undoImport.status, 409);
  } finally { await pool.query("DELETE FROM abastecimento_substituicoes WHERE identificador_externo IN ('990001')"); if (importId || nextImportId) await pool.query('DELETE FROM abastecimento_importacoes WHERE id=ANY($1::uuid[])', [[importId, nextImportId].filter(Boolean)]); await pool.query("DELETE FROM abastecimentos WHERE identificador_externo IN ('990000','990001')"); await new Promise<void>(resolve => server.close(() => resolve())); }
});
