import 'dotenv/config';
import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { app } from '../src/app.js';
import { pool } from '../src/config/database.js';

const suffix = `F3${Date.now().toString().slice(-6)}`;
const created = { entries: [] as string[], destinations: [] as string[], abastecimentos: [] as string[], fleets: [] as string[], prefixes: [] as string[], obras: [] as string[] };
const json = async (response: Response) => response.json() as Promise<any>;

test('Fase 3: transações, concorrência, vínculos e proteção estrutural', async () => {
  assert.equal(process.env.DB_NAME, 'oficina_test');
  const product = (await pool.query<{ id: string }>("SELECT id FROM abastecimento_produtos WHERE codigo='DIESEL_S500' LIMIT 1")).rows[0]!;
  const otherProduct = (await pool.query<{ id: string }>("SELECT id FROM abastecimento_produtos WHERE codigo='DIESEL_S10' LIMIT 1")).rows[0]!;
  const prefix = (await pool.query<{ id: string }>('INSERT INTO prefixos_frota(codigo,descricao,status) VALUES($1,$2,\'ATIVO\') RETURNING id', [`${suffix}-P`, 'Fixture Fase 3'])).rows[0]!; created.prefixes.push(prefix.id);
  const fleetA = (await pool.query<{ id: string }>('INSERT INTO frotas(prefixo_frota_id,numero,codigo,placa,status) VALUES($1,$2,$3,$4,\'ATIVO\') RETURNING id', [prefix.id, '01', `${suffix}-A`, 'TST1A01'])).rows[0]!; created.fleets.push(fleetA.id);
  const fleetB = (await pool.query<{ id: string }>('INSERT INTO frotas(prefixo_frota_id,numero,codigo,placa,status) VALUES($1,$2,$3,$4,\'ATIVO\') RETURNING id', [prefix.id, '02', `${suffix}-B`, 'TST1B02'])).rows[0]!; created.fleets.push(fleetB.id);
  const obra = (await pool.query<{ id: string }>('INSERT INTO obras(codigo,nome,status) VALUES($1,$2,\'ATIVA\') RETURNING id', [`${suffix}-O`, 'Obra Fase 3'])).rows[0]!; created.obras.push(obra.id);
  const server = app.listen(0); const address = server.address(); assert.ok(address && typeof address === 'object'); const base = `http://127.0.0.1:${address.port}`;
  const createEntry = async (fleetId: string, productId = product.id, liters = 10) => { const response = await fetch(`${base}/abastecimento/entradas`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ data_entrada: '2026-09-28', numero_nf: `${suffix}-${created.entries.length}`, produto_id: productId, litros_nf: liters, valor_total_nf: 100, destinos: [{ tipo_destino: 'FROTA_DIRETA', ponto_id: null, frota_id: fleetId, litros: liters }] }) }); assert.equal(response.status, 201); const value = await json(response); created.entries.push(value.id); created.destinations.push(value.destinos[0].id); return value; };
  const manual = async (fleetId: string, productId = product.id, liters = 10, date = '2026-09-28', value = 50) => { const response = await fetch(`${base}/abastecimento/abastecimentos/manual`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ data: date, hora: '08:15', obra_id: obra.id, tipo_destinatario: 'FROTA', frota_id: fleetId, produto_id: productId, litros: liters, valor_total: value, km_hr: 12, horimetro: 3, frentista: 'Fixture F3' }) }); assert.equal(response.status, 201); const valueResponse = await json(response); created.abastecimentos.push(valueResponse.id); return valueResponse; };
  const register = async (destinationId: string, body: Record<string, unknown> = {}) => { const response = await fetch(`${base}/abastecimento/entradas/destinos/${destinationId}/abastecimento`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ data: '2026-09-28', hora: '09:30', obra_id: obra.id, valor_total: 25, ...body }) }); if (response.status === 500) console.error('register 500', await response.clone().text()); return response; };
  const link = async (destinationId: string, abastecimentoId: string) => fetch(`${base}/abastecimento/entradas/destinos/${destinationId}/vincular-abastecimento`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ abastecimento_id: abastecimentoId }) });
  try {
    const direct = await createEntry(fleetA.id); const registered = await register(direct.destinos[0].id); assert.equal(registered.status, 200); const createdRow = (await pool.query('SELECT origem_sistema,identificador_externo,entrada_destino_id,frota_id,produto_id,litros,importacao_id FROM abastecimentos WHERE entrada_destino_id=$1', [direct.destinos[0].id])).rows[0]; assert.equal(createdRow.origem_sistema, 'MANUAL'); assert.match(createdRow.identificador_externo, /^MANUAL-/); assert.equal(createdRow.entrada_destino_id, direct.destinos[0].id); assert.equal(createdRow.frota_id, fleetA.id); assert.equal(createdRow.produto_id, product.id); assert.equal(Number(createdRow.litros), 10); assert.equal(createdRow.importacao_id, null); created.abastecimentos.push((await pool.query<{ id: string }>('SELECT id FROM abastecimentos WHERE entrada_destino_id=$1', [direct.destinos[0].id])).rows[0]!.id);
    assert.equal((await register(direct.destinos[0].id)).status, 409); assert.equal((await pool.query('SELECT count(*)::int AS count FROM abastecimentos WHERE entrada_destino_id=$1', [direct.destinos[0].id])).rows[0].count, 1);

    const concurrent = await createEntry(fleetA.id); const concurrentResults = await Promise.all([register(concurrent.destinos[0].id), register(concurrent.destinos[0].id)]); assert.deepEqual(concurrentResults.map(item => item.status).sort(), [200, 409]); assert.equal((await pool.query('SELECT count(*)::int AS count FROM abastecimentos WHERE entrada_destino_id=$1', [concurrent.destinos[0].id])).rows[0].count, 1); assert.equal((await pool.query("SELECT count(*)::int AS count FROM abastecimentos WHERE origem_sistema='MANUAL' AND entrada_destino_id IS NULL AND obra_id=$1 AND data_hora='2026-09-28 09:30'", [obra.id])).rows[0].count, 0);
    const rollback = await createEntry(fleetA.id); const rollbackResponse = await register(rollback.destinos[0].id, { obra_id: '00000000-0000-4000-8000-000000000000' }); assert.equal(rollbackResponse.status, 404); assert.equal((await pool.query('SELECT count(*)::int AS count FROM abastecimentos WHERE entrada_destino_id=$1', [rollback.destinos[0].id])).rows[0].count, 0);

    const linkTarget = await createEntry(fleetA.id); const existing = await manual(fleetA.id); const before = (await pool.query('SELECT id,origem_sistema,identificador_externo,data_hora,obra_id,litros,valor_total,km_hr,horimetro FROM abastecimentos WHERE id=$1', [existing.id])).rows[0]; assert.equal((await link(linkTarget.destinos[0].id, existing.id)).status, 200); const after = (await pool.query('SELECT id,origem_sistema,identificador_externo,data_hora,obra_id,litros,valor_total,km_hr,horimetro,entrada_destino_id FROM abastecimentos WHERE id=$1', [existing.id])).rows[0]; for (const key of ['id', 'origem_sistema', 'identificador_externo', 'data_hora', 'obra_id', 'litros', 'valor_total', 'km_hr', 'horimetro']) assert.equal(String(after[key]), String(before[key])); assert.equal(after.entrada_destino_id, linkTarget.destinos[0].id);
    const differentFleet = await manual(fleetB.id); assert.equal((await link((await createEntry(fleetA.id)).destinos[0].id, differentFleet.id)).status, 400);
    const differentProduct = await manual(fleetA.id, otherProduct.id); assert.equal((await link((await createEntry(fleetA.id)).destinos[0].id, differentProduct.id)).status, 400);
    const differentLiters = await manual(fleetA.id, product.id, 11); assert.equal((await link((await createEntry(fleetA.id)).destinos[0].id, differentLiters.id)).status, 400);
    const poliTarget = await createEntry(fleetA.id); const poli = (await pool.query<{ id: string }>(`INSERT INTO abastecimentos(origem_sistema,identificador_externo,data_hora,produto_id,obra_id,tipo_destinatario,frota_id,identificacao_original,litros,valor_total,arquivo_nome_original,payload_original) VALUES('POLIFROTA',$1,'2026-09-28 08:00',$2,$3,'FROTA',$4,'POLI-F3',10,40,'POLI-F3','{}'::jsonb) RETURNING id`, [`${suffix}-POLI`, product.id, obra.id, fleetA.id])).rows[0]!; created.abastecimentos.push(poli.id); assert.ok([400, 409].includes((await link(poliTarget.destinos[0].id, poli.id)).status));
    const dateAndValue = await createEntry(fleetA.id); const dated = await manual(fleetA.id, product.id, 10, '2026-09-20', 999); assert.equal((await link(dateAndValue.destinos[0].id, dated.id)).status, 200);
    const reusedManualTarget = await createEntry(fleetA.id); assert.equal((await link(reusedManualTarget.destinos[0].id, existing.id)).status, 409);
    const occupied = await createEntry(fleetA.id); const another = await manual(fleetA.id); assert.equal((await link(linkTarget.destinos[0].id, another.id)).status, 409);
    const protectedEntry = await createEntry(fleetA.id); const protectedManual = await manual(fleetA.id); assert.equal((await link(protectedEntry.destinos[0].id, protectedManual.id)).status, 200); const structural = { data_entrada: '2026-09-29', numero_nf: 'ALTERADA', produto_id: otherProduct.id, litros_nf: 99, valor_total_nf: 1, destinos: [{ tipo_destino: 'FROTA_DIRETA', ponto_id: null, frota_id: fleetB.id, litros: 99 }] }; assert.equal((await fetch(`${base}/abastecimento/entradas/${protectedEntry.id}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(structural) })).status, 409); assert.equal((await fetch(`${base}/abastecimento/entradas/${protectedEntry.id}`, { method: 'DELETE' })).status, 409); const intact = (await pool.query('SELECT d.id,a.entrada_destino_id FROM abastecimento_entrada_destinos d LEFT JOIN abastecimentos a ON a.entrada_destino_id=d.id WHERE d.id=$1', [protectedEntry.destinos[0].id])).rows[0]; assert.equal(intact.id, protectedEntry.destinos[0].id); assert.equal(intact.entrada_destino_id, protectedEntry.destinos[0].id);
    assert.ok(occupied.destinos[0].id);
  } finally { server.close(); }
});

after(async () => { if (process.env.DB_NAME !== 'oficina_test') return; if (created.abastecimentos.length || created.destinations.length) await pool.query('DELETE FROM abastecimentos WHERE id=ANY($1::uuid[]) OR entrada_destino_id=ANY($2::uuid[])', [created.abastecimentos.length ? created.abastecimentos : ['00000000-0000-4000-8000-000000000000'], created.destinations.length ? created.destinations : ['00000000-0000-4000-8000-000000000000']]); if (created.entries.length) { await pool.query('DELETE FROM abastecimento_entrada_destinos WHERE entrada_id=ANY($1::uuid[])', [created.entries]); await pool.query('DELETE FROM abastecimento_entradas WHERE id=ANY($1::uuid[])', [created.entries]); } if (created.fleets.length) await pool.query('DELETE FROM frotas WHERE id=ANY($1::uuid[])', [created.fleets]); if (created.prefixes.length) await pool.query('DELETE FROM prefixos_frota WHERE id=ANY($1::uuid[])', [created.prefixes]); if (created.obras.length) await pool.query('DELETE FROM obras WHERE id=ANY($1::uuid[])', [created.obras]); await pool.end(); });
