import { Router } from 'express';
import * as controller from '../controllers/abastecimentos-base.controller.js';
import { listAbastecimentosHistoricoController } from '../controllers/abastecimentos-historico.controller.js';
import { getRelatorioAbastecimentosController } from '../controllers/abastecimentos-relatorios.controller.js';
import { updateAbastecimentoHistoricoController } from '../controllers/abastecimentos-historico-edit.controller.js';

export const abastecimentoRoutes = Router();
abastecimentoRoutes.get('/produtos', controller.listProdutos);
abastecimentoRoutes.get('/historico', listAbastecimentosHistoricoController);
abastecimentoRoutes.patch('/historico/:id', updateAbastecimentoHistoricoController);
abastecimentoRoutes.get('/relatorios', getRelatorioAbastecimentosController);
abastecimentoRoutes.get('/pontos', controller.listPontos);
abastecimentoRoutes.get('/pontos/:id/produtos', controller.listCompatibilidade);
abastecimentoRoutes.put('/pontos/:id/produtos', controller.replaceCompatibilidade);
abastecimentoRoutes.get('/pontos/:id', controller.getPonto);
abastecimentoRoutes.post('/pontos', controller.createPonto);
abastecimentoRoutes.put('/pontos/:id', controller.updatePonto);
abastecimentoRoutes.patch('/pontos/:id/status', controller.statusPonto);
abastecimentoRoutes.delete('/pontos/:id', controller.deletePonto);
abastecimentoRoutes.get('/terceiros', controller.listTerceiros);
abastecimentoRoutes.get('/terceiros/:id', controller.getTerceiro);
abastecimentoRoutes.post('/terceiros', controller.createTerceiro);
abastecimentoRoutes.put('/terceiros/:id', controller.updateTerceiro);
abastecimentoRoutes.delete('/terceiros/:id', controller.deleteTerceiro);
abastecimentoRoutes.get('/terceiros/:id/identificacoes', controller.listTerceiroIdentificacoesController);
abastecimentoRoutes.post('/terceiros/:id/identificacoes', controller.createTerceiroIdentificacaoController);
abastecimentoRoutes.put('/terceiros/:id/identificacoes/:identificacaoId', controller.updateTerceiroIdentificacaoController);
abastecimentoRoutes.delete('/terceiros/:id/identificacoes/:identificacaoId', controller.deleteTerceiroIdentificacaoController);
abastecimentoRoutes.get('/destinacoes-especiais', controller.listEspeciais);
abastecimentoRoutes.get('/destinacoes-especiais/:id', controller.getEspecial);
abastecimentoRoutes.post('/destinacoes-especiais', controller.createEspecial);
abastecimentoRoutes.put('/destinacoes-especiais/:id', controller.updateEspecial);
abastecimentoRoutes.delete('/destinacoes-especiais/:id', controller.deleteEspecial);
abastecimentoRoutes.get('/entradas', controller.listEntradas);
abastecimentoRoutes.get('/entradas/:id', controller.getEntrada);
abastecimentoRoutes.post('/entradas', controller.createEntrada);
abastecimentoRoutes.put('/entradas/:id', controller.updateEntrada);
abastecimentoRoutes.delete('/entradas/:id', controller.deleteEntrada);
