import { Router } from 'express';
import * as controller from '../controllers/abastecimentos-base.controller.js';
import { listAbastecimentosHistoricoController } from '../controllers/abastecimentos-historico.controller.js';
import { getRelatorioAbastecimentosController } from '../controllers/abastecimentos-relatorios.controller.js';
import { getRelatorioEntradasController } from '../controllers/abastecimentos-entradas-relatorio.controller.js';
import { updateAbastecimentoHistoricoController } from '../controllers/abastecimentos-historico-edit.controller.js';
import { exportAbastecimentosExcelController, exportAbastecimentosPdfController, exportEntradasExcelController, exportEntradasPdfController } from '../controllers/abastecimentos-export.controller.js';
import { getConsumoFrotaController } from '../controllers/abastecimentos-consumo-frota.controller.js';
import { exportConsumoFrotaExcelController, exportConsumoFrotaPdfController } from '../controllers/abastecimentos-export.controller.js';
import * as frotasTerceiras from '../controllers/abastecimentos-frotas-terceiras.controller.js';

export const abastecimentoRoutes = Router();
abastecimentoRoutes.get('/produtos', controller.listProdutos);
abastecimentoRoutes.get('/historico', listAbastecimentosHistoricoController);
abastecimentoRoutes.patch('/historico/:id', updateAbastecimentoHistoricoController);
abastecimentoRoutes.get('/relatorios', getRelatorioAbastecimentosController);
abastecimentoRoutes.get('/relatorios/entradas', getRelatorioEntradasController);
abastecimentoRoutes.get('/relatorios/consumo-frota', getConsumoFrotaController);
abastecimentoRoutes.get('/relatorios/consumo-frota/pdf', exportConsumoFrotaPdfController);
abastecimentoRoutes.get('/relatorios/consumo-frota/excel', exportConsumoFrotaExcelController);
abastecimentoRoutes.get('/relatorios/consumo-frota/exportar/pdf', exportConsumoFrotaPdfController);
abastecimentoRoutes.get('/relatorios/consumo-frota/exportar/excel', exportConsumoFrotaExcelController);
abastecimentoRoutes.get('/relatorios/exportar/pdf', exportAbastecimentosPdfController);
abastecimentoRoutes.get('/relatorios/exportar/excel', exportAbastecimentosExcelController);
abastecimentoRoutes.get('/relatorios/entradas/exportar/pdf', exportEntradasPdfController);
abastecimentoRoutes.get('/relatorios/entradas/exportar/excel', exportEntradasExcelController);
abastecimentoRoutes.get('/pontos', controller.listPontos);
abastecimentoRoutes.get('/pontos/:id/produtos', controller.listCompatibilidade);
abastecimentoRoutes.put('/pontos/:id/produtos', controller.replaceCompatibilidade);
abastecimentoRoutes.get('/pontos/:id', controller.getPonto);
abastecimentoRoutes.post('/pontos', controller.createPonto);
abastecimentoRoutes.put('/pontos/:id', controller.updatePonto);
abastecimentoRoutes.patch('/pontos/:id/status', controller.statusPonto);
abastecimentoRoutes.delete('/pontos/:id', controller.deletePonto);
abastecimentoRoutes.get('/terceiros', controller.listTerceiros);
abastecimentoRoutes.get('/terceiros/:id', controller.getTerceiro);
abastecimentoRoutes.post('/terceiros', controller.createTerceiro);
abastecimentoRoutes.put('/terceiros/:id', controller.updateTerceiro);
abastecimentoRoutes.delete('/terceiros/:id', controller.deleteTerceiro);
abastecimentoRoutes.get('/terceiros/:id/identificacoes', controller.listTerceiroIdentificacoesController);
abastecimentoRoutes.post('/terceiros/:id/identificacoes', controller.createTerceiroIdentificacaoController);
abastecimentoRoutes.put('/terceiros/:id/identificacoes/:identificacaoId', controller.updateTerceiroIdentificacaoController);
abastecimentoRoutes.delete('/terceiros/:id/identificacoes/:identificacaoId', controller.deleteTerceiroIdentificacaoController);
abastecimentoRoutes.get('/frotas-terceiras', frotasTerceiras.list);
abastecimentoRoutes.get('/frotas-terceiras/:id', frotasTerceiras.get);
abastecimentoRoutes.post('/frotas-terceiras', frotasTerceiras.create);
abastecimentoRoutes.put('/frotas-terceiras/:id', frotasTerceiras.update);
abastecimentoRoutes.patch('/frotas-terceiras/:id/status', frotasTerceiras.status);
abastecimentoRoutes.get('/destinacoes-especiais', controller.listEspeciais);
abastecimentoRoutes.get('/destinacoes-especiais/:id', controller.getEspecial);
abastecimentoRoutes.post('/destinacoes-especiais', controller.createEspecial);
abastecimentoRoutes.put('/destinacoes-especiais/:id', controller.updateEspecial);
abastecimentoRoutes.delete('/destinacoes-especiais/:id', controller.deleteEspecial);
abastecimentoRoutes.get('/entradas', controller.listEntradas);
abastecimentoRoutes.get('/entradas/:id', controller.getEntrada);
abastecimentoRoutes.post('/entradas', controller.createEntrada);
abastecimentoRoutes.put('/entradas/:id', controller.updateEntrada);
abastecimentoRoutes.delete('/entradas/:id', controller.deleteEntrada);
