import { Building2, ChartNoAxesCombined, ClipboardList, FileSpreadsheet, Fuel, History, LayoutDashboard, MapPin, Target, Truck, UserRound, Users, X } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import type { NavigationItem } from '../types/navigation'
import itaipuLogo from '../assets/branding/itaipu-engenharia-logo-branca.png'

const navigation: NavigationItem[] = [{ label: 'Dashboard', path: '/', icon: LayoutDashboard }, { label: 'Ordens de Serviço', path: '/ordens-servico', icon: ClipboardList }, { label: 'Importar O.S', path: '/importar-os', icon: FileSpreadsheet }, { label: 'Obras', path: '/obras', icon: Building2 }, { label: 'Funcionários', path: '/funcionarios', icon: Users }, { label: 'Frotas', path: '/frotas', icon: Truck }, { label: 'Relatórios', path: '/relatorios', icon: ChartNoAxesCombined }]
const abastecimentosNavigation: NavigationItem[] = [{ label: 'Histórico', path: '/abastecimentos/historico', icon: History }, { label: 'Relatórios', path: '/abastecimentos/relatorios', icon: ChartNoAxesCombined }, { label: 'Entradas', path: '/abastecimentos/entradas', icon: Fuel }, { label: 'Importar PoliFrota', path: '/abastecimentos/importar-polifrota', icon: FileSpreadsheet }, { label: 'Pontos', path: '/abastecimentos/pontos', icon: MapPin }, { label: 'Terceiros', path: '/abastecimentos/terceiros', icon: UserRound }, { label: 'Destinações Especiais', path: '/abastecimentos/destinacoes-especiais', icon: Target }]
const item = ({ label, path, icon: Icon }: NavigationItem, onClose: () => void) => <NavLink key={path} to={path} className={({ isActive }) => `sidebar__link${isActive ? ' sidebar__link--active' : ''}`} onClick={onClose}><Icon size={20} aria-hidden="true" /><span>{label}</span></NavLink>

export function Sidebar({ open, onClose }: { open: boolean; onClose: () => void }) {
  return <><aside id="main-sidebar" className={`sidebar${open ? ' sidebar--open' : ''}`}><div className="sidebar__brand"><div className="sidebar__brand-identity"><img className="sidebar__brand-logo" src={itaipuLogo} alt="Itaipu Engenharia" /></div><button className="icon-button sidebar__close" type="button" aria-label="Fechar menu de navegação" onClick={onClose}><X size={21} aria-hidden="true" /></button></div><nav className="sidebar__nav" aria-label="Navegação principal"><span className="sidebar__section-label">Oficina</span>{navigation.map(entry => item(entry, onClose))}<span className="sidebar__section-label">Abastecimentos</span>{abastecimentosNavigation.map(entry => item(entry, onClose))}</nav></aside>{open && <button className="sidebar-overlay" type="button" aria-label="Fechar menu" onClick={onClose} />}</>
}
