import { useEffect, useState } from 'react'
import { X } from 'lucide-react'
import axios from 'axios'
import { getAbastecimentosHistorico } from '../../services/abastecimentos'
import type { AbastecimentoHistoricoFilters, AbastecimentoHistoricoResponse } from '../../types/abastecimentos'
import { formatCurrency, formatQuantity } from '../../utils/formatters'
import { formatOptionalQuantity } from '../../utils/historico-display'

type Props = { kind: 'Frota' | 'Obra' | 'Terceiro'; name: string; meta?: string; filters: AbastecimentoHistoricoFilters; onClose: () => void }
const productLabel = (value: string) => value === 'DIESEL_S500' ? 'S500' : value === 'DIESEL_S10' ? 'S10' : value === 'ARLA_32' ? 'ARLA 32' : value
const dateTime = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value))
const errorMessage = (error: unknown) => axios.isAxiosError<{ message?: string }>(error) ? error.response?.data?.message || 'Não foi possível carregar os detalhes.' : 'Não foi possível carregar os detalhes.'

export function AbastecimentosDrilldownModal({ kind, name, meta, filters, onClose }: Props) {
  const [result, setResult] = useState<AbastecimentoHistoricoResponse | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [page, setPage] = useState(1)
  const load = async (nextPage: number) => { setLoading(true); setError(null); try { setResult(await getAbastecimentosHistorico({ ...filters, page: nextPage, limit: 25 })) } catch (e) { setError(errorMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { void load(page) }, [page])
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', onKey); document.body.classList.add('modal-open'); return () => { document.removeEventListener('keydown', onKey); document.body.classList.remove('modal-open') } }, [onClose])
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="order-details abastecimento-drilldown" role="dialog" aria-modal="true" aria-labelledby="abastecimento-drilldown-title"><header><div><span>Detalhamento por {kind}</span><h2 id="abastecimento-drilldown-title">{name}</h2>{meta && <small>{meta}</small>}</div><button className="icon-button" type="button" onClick={onClose} aria-label="Fechar detalhe"><X /></button></header><main>{result && <section className="historico-summary"><Summary label="Abastecimentos" value={String(result.summary.quantidade)} /><Summary label="Litros" value={`${formatQuantity(result.summary.total_litros)} L`} /><Summary label="Valor" value={formatCurrency(result.summary.total_valor)} /></section>}{loading ? <div className="drilldown-state">Carregando detalhes...</div> : error ? <div className="drilldown-state drilldown-state--error"><p>{error}</p><button className="button button--secondary" type="button" onClick={() => void load(page)}>Tentar novamente</button></div> : result?.items.length ? <DetailTable result={result} /> : <div className="drilldown-state">Nenhum abastecimento encontrado para os filtros selecionados.</div>}</main>{result && result.pagination.total > 0 && <footer className="historico-pagination"><button className="button button--secondary" type="button" disabled={page <= 1 || loading} onClick={() => setPage(value => value - 1)}>Anterior</button><span>Página {result.pagination.page} de {result.pagination.total_pages} · {result.pagination.total} registro(s)</span><button className="button button--secondary" type="button" disabled={page >= result.pagination.total_pages || loading} onClick={() => setPage(value => value + 1)}>Próxima</button></footer>}</section></div>
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="historico-summary__item"><span>{label}</span><strong>{value}</strong></div> }
function DetailTable({ result }: { result: AbastecimentoHistoricoResponse }) { return <div className="orders-table-wrap"><table className="orders-table abastecimento-table drilldown-table"><thead><tr><th>Data/Hora</th><th>Nro. Abast.</th><th>Produto</th><th>Litros</th><th>Valor</th><th>Obra</th><th>Frota/Destinatário</th><th>Placa/Identificação</th><th>Km/Hr.</th><th>Horímetro</th><th>Bico</th><th>Frentista</th></tr></thead><tbody>{result.items.map(item => <tr key={item.id}><td>{dateTime(item.data_hora)}</td><td>{item.identificador_externo}</td><td>{productLabel(item.produto_codigo)}</td><td>{formatQuantity(item.litros)} L</td><td>{formatCurrency(item.valor_total)}</td><td>{item.obra_nome}</td><td>{item.destinatario || '-'}</td><td>{item.placa || item.identificacao_original || '-'}</td><td>{formatOptionalQuantity(item.km_hr)}</td><td>{formatOptionalQuantity(item.horimetro)}</td><td>{item.bico_codigo_original || '-'}</td><td>{item.frentista_original || '-'}</td></tr>)}</tbody></table></div> }
