import { useState } from 'react'
import type { PoliFrotaPreviewItem, SubstituicaoAlvo } from '../../types/abastecimentos'
import { markSubstitution, searchSubstitutionTargets } from '../../services/abastecimentos-import'
import { formatCurrency, formatQuantity } from '../../utils/formatters'

type Props = { importId: string; item: PoliFrotaPreviewItem; onClose: () => void; onSaved: (item: PoliFrotaPreviewItem) => void }
const value = (item: PoliFrotaPreviewItem | SubstituicaoAlvo, key: string) => { const raw = (item as unknown as Record<string, unknown>)[key]; return raw === null || raw === undefined || raw === '' ? '—' : String(raw) }

export function SubstitutionModal({ importId, item, onClose, onSaved }: Props) {
  const [query, setQuery] = useState(item.substituicao_identificador_principal || ''), [targets, setTargets] = useState<SubstituicaoAlvo[]>([]), [selected, setSelected] = useState<SubstituicaoAlvo | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null)
  const search = async () => { setBusy(true); setError(null); try { setTargets(await searchSubstitutionTargets({ busca: query })) } catch { setError('Não foi possível buscar abastecimentos existentes.') } finally { setBusy(false) } }
  const save = async () => { if (!selected) return; setBusy(true); setError(null); try { onSaved(await markSubstitution(importId, item.id, selected.id)); onClose() } catch { setError('Não foi possível marcar a substituição.') } finally { setBusy(false) } }
  return <div className="modal-backdrop"><section className="order-form" role="dialog" aria-modal="true" aria-labelledby="substitution-title"><header><div><span>Vínculo explícito</span><h2 id="substitution-title">Marcar como substituição</h2></div><button className="icon-button" type="button" onClick={onClose}>×</button></header><main><p>O novo registro não será contabilizado novamente. Selecione o abastecimento físico já existente.</p><div className="form-grid"><label className="form-field form-field--wide">Nro. Abast., frota ou placa<input value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => event.key === 'Enter' && void search()} placeholder="Ex.: 132982" /></label></div><button className="button button--secondary" type="button" disabled={busy || !query.trim()} onClick={() => void search()}>Pesquisar</button>{error && <p className="form-api-error" role="alert">{error}</p>}<div className="substitution-results">{targets.map(target => <button type="button" className={`substitution-result${selected?.id === target.id ? ' substitution-result--selected' : ''}`} key={target.id} onClick={() => setSelected(target)}><strong>{target.identificador_externo}</strong><span>{target.data_hora} · {target.frota || target.destinatario} · {target.placa || '—'}</span><span>{target.produto} · {formatQuantity(target.litros)} L · {formatCurrency(target.valor_total)} · Bico {target.bico || '—'}</span><small>Obra: {target.obra}</small></button>)}</div>{selected && <div className="substitution-comparison"><strong>NOVO POLIFROTA {item.identificador_externo} → ABASTECIMENTO EXISTENTE {selected.identificador_externo}</strong><span>Data/Hora: {value(item, 'data_hora')} → {selected.data_hora}</span><span>Frota/placa: {value(item, 'frota_original')} / {value(item, 'placa_original')} → {selected.frota || '—'} / {selected.placa || '—'}</span><span>Litros/valor: {value(item, 'litros')} / {value(item, 'valor_total')} → {selected.litros} / {selected.valor_total}</span><span>Bico: {value(item, 'bico_codigo_original')} → {selected.bico || '—'}</span><span>Obra: novo preview → {selected.obra}</span></div>}</main><footer><button className="button button--secondary" type="button" onClick={onClose} disabled={busy}>Cancelar</button><button className="button button--primary" type="button" disabled={!selected || busy} onClick={() => void save()}>Confirmar associação</button></footer></section></div>
}
