import { cloneElement, useEffect, useRef, useState, type ReactElement } from 'react'
import { LoaderCircle, X } from 'lucide-react'
import { getNextProjectCode } from '../../services/projects'
import type { Project, ProjectPayload, ProjectStatus } from '../../types/projects'

type Props = { project: Project | null; saving: boolean; error: string | null; onClose: () => void; onSave: (value: ProjectPayload) => void }
type Form = { codigo: string; nome: string; descricao: string; status: ProjectStatus; data_inicio: string; data_fim: string; observacoes: string }
type Errors = Partial<Record<keyof Form, string>>
const init = (project: Project | null): Form => ({ codigo: project?.codigo || '', nome: project?.nome || '', descricao: project?.descricao || '', status: project?.status || 'ATIVA', data_inicio: project?.data_inicio?.slice(0, 10) || '', data_fim: project?.data_fim?.slice(0, 10) || '', observacoes: project?.observacoes || '' })

export function ProjectFormModal(props: Props) {
  const { saving, onClose } = props
  const [form, setForm] = useState(() => init(props.project))
  const [errors, setErrors] = useState<Errors>({})
  const box = useRef<HTMLFormElement>(null)
  useEffect(() => { const key = (event: KeyboardEvent) => event.key === 'Escape' && !saving && onClose(); document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key) }, [saving, onClose])
  useEffect(() => { if (props.project) return; let active = true; void getNextProjectCode().then((codigo) => active && setForm((current) => current.codigo ? current : { ...current, codigo })).catch(() => undefined); return () => { active = false } }, [props.project])
  const set = (key: keyof Form, value: string) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })) }
  const submit = (event: React.FormEvent) => { event.preventDefault(); const next: Errors = {}; if (!form.codigo.trim()) next.codigo = 'Informe o código da obra.'; else if (form.codigo.trim().length > 50) next.codigo = 'Use no máximo 50 caracteres.'; if (!form.nome.trim()) next.nome = 'Informe o nome da obra.'; else if (form.nome.trim().length > 255) next.nome = 'Use no máximo 255 caracteres.'; if (form.data_inicio && form.data_fim && form.data_fim < form.data_inicio) next.data_fim = 'A data final não pode ser anterior à inicial.'; setErrors(next); if (Object.keys(next).length) { setTimeout(() => box.current?.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus()); return } props.onSave({ codigo: form.codigo.trim(), nome: form.nome.trim(), descricao: form.descricao || null, status: form.status, data_inicio: form.data_inicio || null, data_fim: form.data_fim || null, observacoes: form.observacoes || null }) }
  return <div className="modal-backdrop"><form aria-labelledby="project-form-title" aria-modal="true" className="order-form project-form" onSubmit={submit} ref={box} role="dialog"><header><div><span>{props.project ? 'Editar cadastro' : 'Novo cadastro'}</span><h2 id="project-form-title">{props.project ? 'Editar obra' : 'Nova obra'}</h2></div><button aria-label="Fechar formulário" className="icon-button" disabled={saving} onClick={onClose} type="button"><X /></button></header><main><div className="form-grid"><Field k="codigo" t="Código" e={errors.codigo}><input autoFocus maxLength={50} value={form.codigo} onChange={(event) => set('codigo', event.target.value)} /></Field><Field k="nome" t="Nome" e={errors.nome}><input maxLength={255} value={form.nome} onChange={(event) => set('nome', event.target.value)} /></Field><Field k="status" t="Status"><select value={form.status} onChange={(event) => set('status', event.target.value)}><option value="ATIVA">Ativa</option><option value="INATIVA">Inativa</option></select></Field><Field k="data_inicio" t="Data inicial"><input type="date" value={form.data_inicio} onChange={(event) => set('data_inicio', event.target.value)} /></Field><Field k="data_fim" t="Data final" e={errors.data_fim}><input type="date" value={form.data_fim} onChange={(event) => set('data_fim', event.target.value)} /></Field><label className="form-field form-field--wide">Descrição<textarea rows={3} value={form.descricao} onChange={(event) => set('descricao', event.target.value)} /></label><label className="form-field form-field--wide">Observações<textarea rows={3} value={form.observacoes} onChange={(event) => set('observacoes', event.target.value)} /></label></div>{props.error && <p className="form-api-error" role="alert">{props.error}</p>}</main><footer><button className="button button--secondary" disabled={saving} onClick={onClose} type="button">Cancelar</button><button className="button button--primary" disabled={saving}>{saving ? <><LoaderCircle className="spin" size={16} />Salvando...</> : 'Salvar obra'}</button></footer></form></div>
}
function Field({ k, t, e, children }: { k: keyof Form; t: string; e?: string; children: ReactElement }) { const child = cloneElement(children as ReactElement<Record<string, unknown>>, { id: k, 'aria-invalid': Boolean(e), 'aria-describedby': e ? `${k}-error` : undefined }); return <label className="form-field" htmlFor={k}>{t}{child}{e && <small id={`${k}-error`}>{e}</small>}</label> }
