import type { Request, Response } from 'express';
import { AbastecimentoServiceError } from '../services/abastecimentos-base.service.js';
import { exportAbastecimentosExcel, exportAbastecimentosPdf, exportConsumoFrotaExcel, exportConsumoFrotaPdf, exportEntradasExcel, exportEntradasPdf, exportFilenames } from '../services/abastecimentos-export.service.js';

const text = (value: unknown): string | undefined => value === undefined ? undefined : typeof value === 'string' ? value : (() => { throw new AbastecimentoServiceError(400, 'Filtro deve ser texto.'); })();
const abastecimentos = (request: Request) => ({ data_inicio: text(request.query.data_inicio), data_fim: text(request.query.data_fim), obra_id: text(request.query.obra_id), busca: text(request.query.busca), produto: text(request.query.produto), tipo_destinatario: text(request.query.tipo_destinatario), periodo: text(request.query.periodo) });
const entradas = (request: Request) => ({ data_inicio: text(request.query.data_inicio), data_fim: text(request.query.data_fim), produto_id: text(request.query.produto_id), produto_codigo: text(request.query.produto_codigo), numero_nf: text(request.query.numero_nf), ponto_id: text(request.query.ponto_id), periodo: text(request.query.periodo) as 'dia' | 'mes' | undefined });
const consumoFrota = (request: Request) => ({ data_inicio: text(request.query.data_inicio), data_fim: text(request.query.data_fim), obra_id: text(request.query.obra_id), frota_id: text(request.query.frota_id), produto: text(request.query.produto), tipo_calculo: text(request.query.tipo_calculo) as 'TODOS' | 'KM_L' | 'L_H' | undefined, situacao: text(request.query.situacao) as 'TODAS' | 'CALCULAVEL' | 'PROBLEMATICA' | 'INSUFICIENTE' | undefined });
const send = (response: Response, buffer: Buffer, contentType: string, filename: string): void => { response.setHeader('Content-Type', contentType); response.setHeader('Content-Disposition', `attachment; filename="${filename}"; filename*=UTF-8''${encodeURIComponent(filename)}`); response.status(200).send(buffer); };
const failure = (response: Response, error: unknown): void => { if (error instanceof AbastecimentoServiceError) { response.status(error.statusCode).json({ message: error.message }); return; } console.error('Erro ao exportar relatório de abastecimentos.', error); response.status(500).json({ message: 'Erro interno do servidor.' }); };
export async function exportAbastecimentosPdfController(request: Request, response: Response): Promise<void> { try { const filters = abastecimentos(request); send(response, await exportAbastecimentosPdf(filters), 'application/pdf', exportFilenames.abastecimentos(filters, 'pdf')); } catch (error) { failure(response, error); } }
export async function exportAbastecimentosExcelController(request: Request, response: Response): Promise<void> { try { const filters = abastecimentos(request); send(response, await exportAbastecimentosExcel(filters), 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', exportFilenames.abastecimentos(filters, 'xlsx')); } catch (error) { failure(response, error); } }
export async function exportEntradasPdfController(request: Request, response: Response): Promise<void> { try { const filters = entradas(request); send(response, await exportEntradasPdf(filters), 'application/pdf', exportFilenames.entradas(filters, 'pdf')); } catch (error) { failure(response, error); } }
export async function exportEntradasExcelController(request: Request, response: Response): Promise<void> { try { const filters = entradas(request); send(response, await exportEntradasExcel(filters), 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', exportFilenames.entradas(filters, 'xlsx')); } catch (error) { failure(response, error); } }
export async function exportConsumoFrotaPdfController(request: Request, response: Response): Promise<void> { try { const filters = consumoFrota(request); send(response, await exportConsumoFrotaPdf(filters), 'application/pdf', exportFilenames.consumoFrota(filters, 'pdf')); } catch (error) { failure(response, error); } }
export async function exportConsumoFrotaExcelController(request: Request, response: Response): Promise<void> { try { const filters = consumoFrota(request); send(response, await exportConsumoFrotaExcel(filters), 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', exportFilenames.consumoFrota(filters, 'xlsx')); } catch (error) { failure(response, error); } }
