import type { Request, Response } from 'express';
import { analyzePoliFrota, assertImportacaoPodeContinuar, AbastecimentoImportError, cancelImportacao, confirmImportSafe, getImportacao, listImportacoesEmAndamento, markSubstitution, removeSubstitution, resolveBatch, resolveItem, searchSubstitutionTargets } from '../services/abastecimentos-import.service.js';

const sendError = (response: Response, error: unknown): void => { if (error instanceof AbastecimentoImportError) { response.status(error.statusCode).json({ message: error.message }); return; } console.error('Erro interno na importação PoliFrota.'); response.status(500).json({ message: 'Erro interno do servidor.' }); };
const routeId = (value: string | string[] | undefined, field: string): string => { if (typeof value !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) throw new AbastecimentoImportError(400, `${field} deve ser um UUID válido.`); return value; };

export async function analyzePoliFrotaController(request: Request, response: Response): Promise<void> { try { const file = (request as Request & { file?: { buffer: Buffer; originalname: string } }).file; if (!file) { response.status(400).json({ message: 'Envie um arquivo XLS ou XLSX no campo arquivo.' }); return; } response.status(201).json(await analyzePoliFrota(file.buffer, file.originalname, request.query.nova_analise === 'true')); } catch (error) { sendError(response, error); } }
export async function listImportacoesEmAndamentoController(_request: Request, response: Response): Promise<void> { try { response.json(await listImportacoesEmAndamento()); } catch (error) { sendError(response, error); } }
export async function getImportacaoController(request: Request, response: Response): Promise<void> { try { response.json(await getImportacao(routeId(request.params.id, 'id'))); } catch (error) { sendError(response, error); } }
export async function cancelImportacaoController(request: Request, response: Response): Promise<void> { try { response.json(await cancelImportacao(routeId(request.params.id, 'importacao_id'))); } catch (error) { sendError(response, error); } }
export async function resolveItemController(request: Request, response: Response): Promise<void> { try { const id = routeId(request.params.id, 'importacao_id'); await assertImportacaoPodeContinuar(id); response.json(await resolveItem(id, routeId(request.params.itemId, 'item_id'), request.body)); } catch (error) { sendError(response, error); } }
export async function resolveBatchController(request: Request, response: Response): Promise<void> { try { const id = routeId(request.params.id, 'importacao_id'); await assertImportacaoPodeContinuar(id); response.json(await resolveBatch(id, request.body)); } catch (error) { sendError(response, error); } }
export async function confirmImportController(request: Request, response: Response): Promise<void> { try { const id = routeId(request.params.id, 'importacao_id'); await assertImportacaoPodeContinuar(id); response.json(await confirmImportSafe(id, request.body)); } catch (error) { sendError(response, error); } }
export async function searchSubstitutionTargetsController(request: Request, response: Response): Promise<void> { try { response.json(await searchSubstitutionTargets({ busca: typeof request.query.busca === 'string' ? request.query.busca : undefined, data_inicio: typeof request.query.data_inicio === 'string' ? request.query.data_inicio : undefined, data_fim: typeof request.query.data_fim === 'string' ? request.query.data_fim : undefined })); } catch (error) { sendError(response, error); } }
export async function markSubstitutionController(request: Request, response: Response): Promise<void> { try { const id = routeId(request.params.id, 'importacao_id'); await assertImportacaoPodeContinuar(id); const targetId = request.body?.abastecimento_id; if (typeof targetId !== 'string') throw new AbastecimentoImportError(400, 'Informe o abastecimento alvo.'); response.json(await markSubstitution(id, routeId(request.params.itemId, 'item_id'), routeId(targetId, 'abastecimento_id'))); } catch (error) { sendError(response, error); } }
export async function removeSubstitutionController(request: Request, response: Response): Promise<void> { try { const id = routeId(request.params.id, 'importacao_id'); await assertImportacaoPodeContinuar(id); response.json(await removeSubstitution(id, routeId(request.params.itemId, 'item_id'))); } catch (error) { sendError(response, error); } }
