import { useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { EntradaDetailsModal } from '../components/abastecimentos/EntradaDetailsModal'
import { EntradaFormModal } from '../components/abastecimentos/EntradaFormModal'
import { ErrorState } from '../components/ErrorState'
import { OrdersLoading } from '../components/orders/OrdersLoading'
import { PageHeader } from '../components/PageHeader'
import { createEntrada, deleteEntrada, getAbastecimentoProdutos, getEntrada, getEntradas, getPontoProdutos, getPontos, updateEntrada } from '../services/abastecimentos'
import type { AbastecimentoProduto, Entrada, EntradaFilters, EntradaPayload, PontoOperacional } from '../types/abastecimentos'
import { formatCurrency, formatDate, formatQuantity } from '../utils/formatters'

const message = (error: unknown, fallback: string) => axios.isAxiosError<{ message?: string }>(error) && [400, 404, 409].includes(error.response?.status ?? 0) ? error.response?.data?.message || fallback : fallback

export function AbastecimentosEntradasPage() {
  const [entradas, setEntradas] = useState<Entrada[]>([]), [produtos, setProdutos] = useState<AbastecimentoProduto[]>([]), [pontos, setPontos] = useState<PontoOperacional[]>([])
  const [compatibilidades, setCompatibilidades] = useState<Record<string, string[]>>({}), [loading, setLoading] = useState(true), [error, setError] = useState(false)
  const [filters, setFilters] = useState<EntradaFilters>({}), [form, setForm] = useState<Entrada | null | undefined>(undefined), [details, setDetails] = useState<Entrada | null>(null)
  const [saving, setSaving] = useState(false), [formError, setFormError] = useState<string | null>(null), [confirm, setConfirm] = useState<Entrada | null>(null), [busy, setBusy] = useState(false), [success, setSuccess] = useState<string | null>(null)

  const load = async () => { setLoading(true); setError(false); try { const [nextEntradas, nextProdutos, nextPontos] = await Promise.all([getEntradas(filters), getAbastecimentoProdutos(), getPontos()]); setEntradas(nextEntradas); setProdutos(nextProdutos); setPontos(nextPontos); const pairs = await Promise.all(nextPontos.map(async ponto => [ponto.id, (await getPontoProdutos(ponto.id)).map(product => product.id)] as const)); setCompatibilidades(Object.fromEntries(pairs)) } catch { setError(true) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const applyFilters = async (event: React.FormEvent) => { event.preventDefault(); await load() }
  const updateFilter = (key: keyof EntradaFilters, value: string) => setFilters(current => ({ ...current, [key]: value || undefined }))
  const save = async (payload: EntradaPayload) => { if (saving || form === undefined) return; setSaving(true); setFormError(null); try { if (form) await updateEntrada(form.id, payload); else await createEntrada(payload); setForm(undefined); setSuccess('Entrada salva com sucesso.'); await load() } catch (e) { setFormError(message(e, 'Não foi possível salvar a entrada.')) } finally { setSaving(false) } }
  const edit = async (id: string) => { try { setForm(await getEntrada(id)); setFormError(null) } catch (e) { setSuccess(message(e, 'Não foi possível carregar a entrada.')) } }
  const remove = async () => { if (!confirm || busy) return; setBusy(true); try { await deleteEntrada(confirm.id); setConfirm(null); setSuccess('Entrada excluída com sucesso.'); await load() } catch (e) { setSuccess(message(e, 'Não foi possível excluir a entrada.')) } finally { setBusy(false) } }
  const clear = () => { setFilters({}); setTimeout(() => void load(), 0) }
  const productOptions = useMemo(() => produtos.filter(item => item.permite_entrada), [produtos])

  return <><PageHeader title="Entradas de Combustível" subtitle="Registre notas fiscais e distribua diesel pelos pontos operacionais." action={<button className="button button--primary" onClick={() => { setFormError(null); setForm(null) }}><Plus size={18} />Nova entrada</button>} />
    {success && <div className="success-banner" role="status">{success}</div>}
    <form className="orders-filters abastecimento-filters" onSubmit={applyFilters}><header><h2>Filtros</h2><p>Encontre entradas por período, produto, NF ou ponto.</p></header><div className="orders-filters__grid"><label>Data inicial<input type="date" value={filters.data_inicio || ''} onChange={e => updateFilter('data_inicio', e.target.value)} /></label><label>Data final<input type="date" value={filters.data_fim || ''} onChange={e => updateFilter('data_fim', e.target.value)} /></label><label>Produto<select value={filters.produto_id || ''} onChange={e => updateFilter('produto_id', e.target.value)}><option value="">Todos</option>{productOptions.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label>Número da NF<input value={filters.numero_nf || ''} onChange={e => updateFilter('numero_nf', e.target.value)} /></label><label>Ponto de recebimento<select value={filters.ponto_id || ''} onChange={e => updateFilter('ponto_id', e.target.value)}><option value="">Todos</option>{pontos.map(item => <option key={item.id} value={item.id}>{item.codigo} — {item.nome}</option>)}</select></label></div><footer><button className="button button--secondary" type="button" onClick={clear}>Limpar filtros</button><button className="button button--primary">Aplicar filtros</button></footer></form>
    <section className="orders-results" aria-live="polite"><header><div><h2>Entradas registradas</h2><p>{!loading && !error ? `${entradas.length} registro(s) encontrado(s)` : 'Consulta às entradas de combustível'}</p></div></header>{loading ? <OrdersLoading /> : error ? <ErrorState message="Não foi possível carregar as entradas." onRetry={() => void load()} /> : entradas.length ? <EntradaTable entradas={entradas} onView={setDetails} onEdit={id => void edit(id)} onDelete={setConfirm} /> : <div className="orders-message"><Search /><div><h3>Nenhuma entrada encontrada.</h3><p>Cadastre uma entrada ou revise os filtros informados.</p></div></div>}</section>
    {form !== undefined && <EntradaFormModal entrada={form} produtos={productOptions} pontos={pontos} compatibilidades={compatibilidades} saving={saving} error={formError} onClose={() => !saving && setForm(undefined)} onSave={payload => void save(payload)} />}{details && <EntradaDetailsModal entrada={details} onClose={() => setDetails(null)} />}{confirm && <ConfirmDialog title="Excluir entrada?" message="Tem certeza que deseja excluir esta entrada?" busy={busy} error={null} confirmLabel="Excluir" busyLabel="Excluindo..." onCancel={() => !busy && setConfirm(null)} onConfirm={() => void remove()} />}
  </>
}

function EntradaTable({ entradas, onView, onEdit, onDelete }: { entradas: Entrada[]; onView: (entrada: Entrada) => void; onEdit: (id: string) => void; onDelete: (entrada: Entrada) => void }) { return <><div className="orders-table-wrap"><table className="orders-table abastecimento-table"><thead><tr><th>Data</th><th>NF</th><th>Produto</th><th>Litros NF</th><th>Total distribuído</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{entradas.map(entrada => <tr key={entrada.id}><td>{formatDate(entrada.data_entrada)}</td><td><strong>{entrada.numero_nf}</strong></td><td>{entrada.produto.nome}</td><td>{formatQuantity(entrada.litros_nf)} L</td><td>{entrada.produto.codigo === 'ARLA_32' ? '—' : `${formatQuantity(entrada.total_distribuido)} L`}</td><td>{formatCurrency(entrada.valor_total_nf)}</td><td><span className="order-actions"><button className="button button--secondary" title="Visualizar" onClick={() => onView(entrada)}><Eye size={16} /></button><button className="button button--edit" title="Editar" onClick={() => onEdit(entrada.id)}><Pencil size={16} /></button><button className="button button--danger" title="Excluir" onClick={() => onDelete(entrada)}><Trash2 size={16} /></button></span></td></tr>)}</tbody></table></div><div className="orders-mobile-list">{entradas.map(entrada => <article className="order-mobile-card" key={entrada.id}><header><div><small>{formatDate(entrada.data_entrada)}</small><strong>{entrada.numero_nf}</strong></div><span className="status-badge status-badge--finalizada">{entrada.produto.nome}</span></header><dl><div><dt>Litros NF</dt><dd>{formatQuantity(entrada.litros_nf)} L</dd></div><div><dt>Total distribuído</dt><dd>{entrada.produto.codigo === 'ARLA_32' ? '—' : `${formatQuantity(entrada.total_distribuido)} L`}</dd></div><div><dt>Valor</dt><dd>{formatCurrency(entrada.valor_total_nf)}</dd></div></dl><span className="order-actions"><button className="button button--secondary" onClick={() => onView(entrada)}>Visualizar</button><button className="button button--edit" onClick={() => onEdit(entrada.id)}>Editar</button><button className="button button--danger" onClick={() => onDelete(entrada)}>Excluir</button></span></article>)}</div></> }
