import { useEffect, useState } from 'react'
import axios from 'axios'
import { ChevronDown, ChevronUp, Search } from 'lucide-react'
import { ErrorState } from '../components/ErrorState'
import { OrdersLoading } from '../components/orders/OrdersLoading'
import { PageHeader } from '../components/PageHeader'
import { HistoricoEditModal } from '../components/abastecimentos/HistoricoEditModal'
import { getAbastecimentoProdutos, getAbastecimentosHistorico, getDestinacoesEspeciais, getTerceiros } from '../services/abastecimentos'
import { getFleets } from '../services/fleets'
import { getProjects } from '../services/projects'
import type { AbastecimentoHistoricoFilters, AbastecimentoHistoricoItem, AbastecimentoHistoricoResponse, AbastecimentoProduto, DestinacaoEspecial, DestinatarioTipo, Terceiro } from '../types/abastecimentos'
import type { Fleet } from '../types/fleets'
import type { Project } from '../types/projects'
import { formatCurrency, formatQuantity } from '../utils/formatters'
import { formatOptionalQuantity } from '../utils/historico-display'

const products = [{ value: '', label: 'Todos' }, { value: 'DIESEL_S500', label: 'S500' }, { value: 'DIESEL_S10', label: 'S10' }, { value: 'ARLA_32', label: 'ARLA 32' }]
const recipientTypes = [{ value: '', label: 'Todos' }, { value: 'FROTA', label: 'Frota' }, { value: 'TERCEIRO', label: 'Terceiro' }, { value: 'ESPECIAL', label: 'Especial' }, { value: 'EXTERNA', label: 'Externa' }]
const blankFilters = (): AbastecimentosHistoricoForm => ({ data_inicio: '', data_fim: '', obra_id: '', busca: '', produto: '', tipo_destinatario: '', limit: 50 })
const formatDateTime = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value))
const errorMessage = (error: unknown) => axios.isAxiosError<{ message?: string }>(error) ? error.response?.data?.message || 'Não foi possível consultar o histórico.' : 'Não foi possível consultar o histórico.'

export function AbastecimentosHistoricoPage() {
  const [filters, setFilters] = useState<AbastecimentosHistoricoForm>(blankFilters())
  const [result, setResult] = useState<AbastecimentoHistoricoResponse | null>(null)
  const [projects, setProjects] = useState<Project[]>([]), [fleets, setFleets] = useState<Fleet[]>([]), [thirds, setThirds] = useState<Terceiro[]>([]), [specials, setSpecials] = useState<DestinacaoEspecial[]>([]), [productOptions, setProductOptions] = useState<AbastecimentoProduto[]>([])
  const [editing, setEditing] = useState<AbastecimentoHistoricoItem | null>(null), [saving, setSaving] = useState(false), [editError, setEditError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null)
  const load = async (nextFilters = filters, page = 1) => { setLoading(true); setError(null); try { const [nextResult, nextProjects, nextFleets, nextThirds, nextSpecials, nextProducts] = await Promise.all([getAbastecimentosHistorico(toQuery(nextFilters, page)), projects.length ? Promise.resolve(projects) : getProjects(), fleets.length ? Promise.resolve(fleets) : getFleets(), thirds.length ? Promise.resolve(thirds) : getTerceiros(), specials.length ? Promise.resolve(specials) : getDestinacoesEspeciais(), productOptions.length ? Promise.resolve(productOptions) : getAbastecimentoProdutos()]); setResult(nextResult); setProjects(nextProjects); setFleets(nextFleets); setThirds(nextThirds); setSpecials(nextSpecials); setProductOptions(nextProducts) } catch (e) { setError(errorMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const update = (key: keyof AbastecimentosHistoricoForm, value: string) => setFilters(current => ({ ...current, [key]: value }))
  const saveDone = () => { setEditing(null); setEditError(null); void load(filters, result?.pagination.page || 1) }
  return <><PageHeader title="Histórico de Abastecimentos" subtitle="Consulte os abastecimentos efetivamente confirmados no sistema." />
    <form className="orders-filters abastecimento-filters historico-filters" onSubmit={event => { event.preventDefault(); void load(filters, 1) }}><header><h2>Filtros</h2><p>Pesquise por período, obra, produto ou qualquer identificação do destinatário.</p></header><div className="orders-filters__grid"><label>Data inicial<input type="date" value={filters.data_inicio} onChange={e => update('data_inicio', e.target.value)} /></label><label>Data final<input type="date" value={filters.data_fim} onChange={e => update('data_fim', e.target.value)} /></label><label>Obra<select value={filters.obra_id} onChange={e => update('obra_id', e.target.value)}><option value="">Todas</option>{projects.filter(item => item.status === 'ATIVA').map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label>Frota / destinatário<input placeholder="CE02C, CATARINA, JVD5J65..." value={filters.busca} onChange={e => update('busca', e.target.value)} /></label><label>Produto<select value={filters.produto} onChange={e => update('produto', e.target.value)}>{products.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>Tipo de destinatário<select value={filters.tipo_destinatario} onChange={e => update('tipo_destinatario', e.target.value)}>{recipientTypes.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div><footer><button className="button button--secondary" type="button" onClick={() => { const next = blankFilters(); setFilters(next); void load(next, 1) }}>Limpar filtros</button><button className="button button--primary" type="submit">Aplicar filtros</button></footer></form>
    {result && <section className="historico-summary" aria-live="polite"><Summary label="Abastecimentos" value={String(result.summary.quantidade)} /><Summary label="Litros" value={`${formatQuantity(result.summary.total_litros)} L`} /><Summary label="Valor" value={formatCurrency(result.summary.total_valor)} /></section>}
    <section className="orders-results historico-results" aria-live="polite"><header><div><h2>Abastecimentos confirmados</h2><p>{result ? `${result.pagination.total} registro(s) encontrado(s)` : 'Consulta ao histórico'}</p></div></header>{loading ? <OrdersLoading /> : error ? <ErrorState message={error} onRetry={() => void load()} /> : result?.items.length ? <HistoricoTable items={result.items} onEdit={item => { setEditError(null); setEditing(item) }} /> : <div className="orders-message"><Search /><div><h3>Nenhum abastecimento encontrado.</h3><p>Revise os filtros informados.</p></div></div>}{result && result.pagination.total > 0 && <Pagination pagination={result.pagination} onChange={page => void load(filters, page)} onLimitChange={limit => { const next = { ...filters, limit }; setFilters(next); void load(next, 1) }} />}</section>
    {editing && <HistoricoEditModal item={editing} projects={projects} fleets={fleets} thirds={thirds} specials={specials} products={productOptions} saving={saving} error={editError} onClose={() => setEditing(null)} onSaved={saveDone} onSaving={setSaving} onError={setEditError} />}
  </>
}
type AbastecimentosHistoricoForm = Omit<AbastecimentoHistoricoFilters, 'page' | 'limit' | 'tipo_destinatario'> & { tipo_destinatario: '' | DestinatarioTipo; limit: 25 | 50 | 100 }
const toQuery = (filters: AbastecimentosHistoricoForm, page: number): AbastecimentoHistoricoFilters => ({ ...filters, data_inicio: filters.data_inicio || undefined, data_fim: filters.data_fim || undefined, obra_id: filters.obra_id || undefined, busca: filters.busca || undefined, produto: filters.produto || undefined, tipo_destinatario: filters.tipo_destinatario || undefined, page, limit: filters.limit })
function Summary({ label, value }: { label: string; value: string }) { return <div className="historico-summary__item"><span>{label}</span><strong>{value}</strong></div> }
function HistoricoTable({ items, onEdit }: { items: AbastecimentoHistoricoItem[]; onEdit: (item: AbastecimentoHistoricoItem) => void }) { const [expanded, setExpanded] = useState<string | null>(null); return <div className="orders-table-wrap"><table className="orders-table abastecimento-table historico-table"><thead><tr><th></th><th>Data/Hora</th><th>Frota/Destinatário</th><th>Placa</th><th>Produto</th><th>Litros</th><th>Valor</th><th>Km/Hr.</th><th>Horímetro</th><th>Bico</th><th>Obra</th><th>Ações</th></tr></thead><tbody>{items.map(item => <>{<tr key={item.id} className="historico-row" onClick={() => setExpanded(expanded === item.id ? null : item.id)}><td>{expanded === item.id ? <ChevronUp size={16} /> : <ChevronDown size={16} />}</td><td>{formatDateTime(item.data_hora)}</td><td><strong>{item.destinatario || '-'}</strong><small className="historico-type">{item.tipo_destinatario}</small></td><td>{item.placa || '-'}</td><td>{productLabel(item.produto_codigo)}</td><td>{formatQuantity(item.litros)} L</td><td>{formatCurrency(item.valor_total)}</td><td>{formatOptionalQuantity(item.km_hr)}</td><td>{formatOptionalQuantity(item.horimetro)}</td><td>{item.bico_codigo_original || '-'}</td><td>{item.obra_nome}</td><td><button className="button button--secondary" type="button" onClick={event => { event.stopPropagation(); onEdit(item) }}>Editar</button></td></tr>}{expanded === item.id && <tr key={`${item.id}-details`} className="historico-detail-row"><td colSpan={12}><strong>Detalhes do abastecimento</strong><span>Nro. Abast.: {item.identificador_externo}</span><span>Frentista: {item.frentista_original || '-'}</span><span>Origem: {item.origem_sistema}</span></td></tr>}</>)}</tbody></table></div> }
function productLabel(value: string) { return value === 'DIESEL_S500' ? 'S500' : value === 'DIESEL_S10' ? 'S10' : value === 'ARLA_32' ? 'ARLA 32' : value }
function Pagination({ pagination, onChange, onLimitChange }: { pagination: AbastecimentoHistoricoResponse['pagination']; onChange: (page: number) => void; onLimitChange: (limit: 25 | 50 | 100) => void }) { return <footer className="historico-pagination"><button className="button button--secondary" disabled={pagination.page <= 1} onClick={() => onChange(pagination.page - 1)}>Anterior</button><span>Página {pagination.page} de {pagination.total_pages}</span><button className="button button--secondary" disabled={pagination.page >= pagination.total_pages} onClick={() => onChange(pagination.page + 1)}>Próxima</button><select value={pagination.limit} onChange={event => onLimitChange(Number(event.target.value) as 25 | 50 | 100)} aria-label="Registros por página"><option value={25}>25 por página</option><option value={50}>50 por página</option><option value={100}>100 por página</option></select></footer> }
