import { useEffect, useMemo, useState } from 'react'
import { CircleDollarSign, Package, Wrench } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { OrderDetailsModal } from '../components/orders/OrderDetailsModal'
import { OrdersReportTable } from '../components/reports/OrdersReportTable'
import { ReportsFilters } from '../components/reports/ReportsFilters'
import { ReportsExportMenu } from '../components/reports/ReportsExportMenu'
import { ReportSection } from '../components/reports/ReportSection'
import { getFleetPrefixes, getProjects, getServiceOrderDetails, getServiceOrders } from '../services/orders'
import type { FleetPrefixOption, ProjectOption, ServiceOrder, ServiceOrderDetails } from '../types/orders'
import type { ExpensesByProject, ReportFilters } from '../types/reports'
import { formatCurrency } from '../utils/formatters'

const money=(o:ServiceOrder,key:'total_mao_obra_interna'|'total_servicos_terceiros'|'total_produtos'|'total_os')=>o.status==='CANCELADA'?0:Number(o[key])
export function RelatoriosPage(){
 const[draft,setDraft]=useState<ReportFilters>({}),[applied,setApplied]=useState<ReportFilters>({}),[periodError,setPeriodError]=useState(''),[projects,setProjects]=useState<ProjectOption[]>([]),[prefixes,setPrefixes]=useState<FleetPrefixOption[]>([]),[orders,setOrders]=useState<ServiceOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false),[selected,setSelected]=useState<string|null>(null),[details,setDetails]=useState<ServiceOrderDetails|null>(null),[detailsError,setDetailsError]=useState(false)
 useEffect(()=>{const c=new AbortController();Promise.all([getProjects(c.signal),getFleetPrefixes(c.signal)]).then(([a,b])=>{setProjects(a);setPrefixes(b)}).catch(()=>undefined);return()=>c.abort()},[])
 useEffect(()=>{const c=new AbortController();queueMicrotask(async()=>{setLoading(true);setError(false);try{setOrders(await getServiceOrders(applied,c.signal))}catch{if(!c.signal.aborted)setError(true)}finally{if(!c.signal.aborted)setLoading(false)}});return()=>c.abort()},[applied])
 const summary=useMemo(()=>orders.reduce((a,o)=>({labor:a.labor+money(o,'total_mao_obra_interna'),third:a.third+money(o,'total_servicos_terceiros'),products:a.products+money(o,'total_produtos'),total:a.total+money(o,'total_os')}),{labor:0,third:0,products:0,total:0}),[orders])
 const byProject=useMemo(()=>Array.from(orders.reduce((map,o)=>{if(o.status==='CANCELADA')return map;const current=map.get(o.obra_id)||{obra_id:o.obra_id,obra_codigo:o.obra_codigo,obra_nome:o.obra_nome,total_mao_obra_interna:0,total_servicos_terceiros:0,total_produtos:0,total_gasto:0,quantidade_os:0};current.total_mao_obra_interna+=Number(o.total_mao_obra_interna);current.total_servicos_terceiros+=Number(o.total_servicos_terceiros);current.total_produtos+=Number(o.total_produtos);current.total_gasto+=Number(o.total_os);current.quantidade_os++;map.set(o.obra_id,current);return map},new Map<string,ExpensesByProject>()).values()).sort((a,b)=>b.total_gasto-a.total_gasto),[orders])
 const projectRows=byProject.length?[...byProject,{obra_id:'TOTAL',obra_codigo:'',obra_nome:'TOTAL',total_mao_obra_interna:summary.labor,total_servicos_terceiros:summary.third,total_produtos:summary.products,total_gasto:summary.total,quantidade_os:orders.filter(o=>o.status!=='CANCELADA').length}]:[]
 const apply=()=>{if(draft.data_inicio&&draft.data_fim&&draft.data_fim<draft.data_inicio){setPeriodError('A data final não pode ser anterior à data inicial.');return}setPeriodError('');setApplied({...draft})},clear=()=>{setPeriodError('');setDraft({});setApplied({})}
 const open=async(id:string)=>{setSelected(id);setDetails(null);setDetailsError(false);try{setDetails(await getServiceOrderDetails(id))}catch{setDetailsError(true)}}
 const cards=[{label:'Mão de obra',value:formatCurrency(summary.labor),icon:Wrench},{label:'Produtos / Materiais',value:formatCurrency(summary.products),icon:Package},{label:'Serviços terceirizados',value:formatCurrency(summary.third),icon:CircleDollarSign},{label:'Total apropriado',value:formatCurrency(summary.total),icon:CircleDollarSign,tone:'amber' as const}]
 return <><PageHeader title="Relatórios" subtitle="Análise dos valores apropriados às obras pela oficina." action={<ReportsExportMenu filters={applied}/>}/><ReportsFilters draft={draft} projects={projects} prefixes={prefixes} error={periodError} onChange={setDraft} onApply={apply} onClear={clear}/>{error?<section className="report-state report-state--error"><p>Não foi possível carregar o relatório.</p><button className="button button--secondary" onClick={()=>setApplied({...applied})}>Tentar novamente</button></section>:<>{loading?<div className="report-loading reports-stats-loading" aria-label="Carregando resumo"><span/><span/><span/></div>:<div className="reports-stats reports-stats--financial reports-stats--standalone">{cards.map(x=><StatCard key={x.label}{...x}/>)}</div>}<ReportSection kind="project" title="Apropriação por obra" description="Mão de obra, terceiros, produtos e total apropriado, em ordem decrescente." rows={projectRows} loading={loading} error={false} downloads={{excel:false,pdf:false}} downloadError="" onRetry={()=>setApplied({...applied})} onDownload={()=>undefined} showExports={false}/>{!loading&&<OrdersReportTable orders={orders} onOpen={id=>void open(id)}/>}</>}{selected&&<OrderDetailsModal readOnly order={details} loading={!details&&!detailsError} error={detailsError} onClose={()=>setSelected(null)} onRetry={()=>void open(selected)} onDelete={()=>undefined} onMutated={async()=>{setDetails(await getServiceOrderDetails(selected))}}/>}</>
}